// SPDX-FileCopyrightText: 2026 Shubham Sharma
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Pure-Dart contact sheet: reads test/golden/goldens/*.png and writes
// test/golden/gallery/index.html (open with file:// — no server).

import 'dart:io';

void main(List<String> args) {
  final root = Directory.current;
  final goldensDir = Directory.fromUri(root.uri.resolve('test/golden/goldens/'));
  final outDir = Directory.fromUri(root.uri.resolve('test/golden/gallery/'));
  final outFile = File.fromUri(outDir.uri.resolve('index.html'));

  if (!goldensDir.existsSync()) {
    stderr.writeln('No goldens dir at ${goldensDir.path}');
    exit(1);
  }
  outDir.createSync(recursive: true);

  final files = goldensDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.toLowerCase().endsWith('.png'))
      .toList()
    ..sort((a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last));

  // group by screen prefix: name without trailing _light|_dark|_fa_rtl
  final groups = <String, List<File>>{};
  for (final f in files) {
    final base = f.uri.pathSegments.last.replaceAll(RegExp(r'\.png$'), '');
    final screen = base
        .replaceAll(RegExp(r'_fa_rtl$'), '')
        .replaceAll(RegExp(r'_light$'), '')
        .replaceAll(RegExp(r'_dark$'), '');
    groups.putIfAbsent(screen, () => []).add(f);
  }

  final keys = groups.keys.toList()..sort();

  final buf = StringBuffer()
    ..writeln('<!DOCTYPE html>')
    ..writeln('<html lang="en">')
    ..writeln('<head>')
    ..writeln('<meta charset="utf-8">')
    ..writeln('<meta name="viewport" content="width=device-width, initial-scale=1">')
    ..writeln('<title>GitJournal golden gallery</title>')
    ..writeln('<style>')
    ..writeln('''
body { font-family: system-ui, sans-serif; margin: 1.5rem; background: #111; color: #eee; }
h1 { font-size: 1.4rem; margin-bottom: 0.25rem; }
.meta { color: #aaa; margin-bottom: 1.5rem; font-size: 0.9rem; }
section { margin-bottom: 2rem; border-top: 1px solid #333; padding-top: 1rem; }
section h2 { font-size: 1.1rem; margin: 0 0 0.75rem; color: #9cf; }
.grid { display: flex; flex-wrap: wrap; gap: 1rem; }
.card { background: #1c1c1c; border-radius: 8px; padding: 0.5rem; max-width: 220px; }
.card img { display: block; width: 200px; height: auto; border-radius: 4px; background: #000; }
.card .label { font-size: 0.75rem; margin-top: 0.4rem; color: #ccc; word-break: break-all; }
nav { margin-bottom: 1.5rem; }
nav a { color: #9cf; margin-right: 0.75rem; font-size: 0.85rem; }
''')
    ..writeln('</style>')
    ..writeln('</head>')
    ..writeln('<body>')
    ..writeln('<h1>GitJournal golden gallery</h1>')
    ..writeln(
        '<p class="meta">${files.length} images · ${keys.length} screens · generated by tool/generate_golden_gallery.dart</p>')
    ..writeln('<nav>');

  for (final k in keys) {
    buf.writeln('<a href="#$k">$k</a>');
  }
  buf.writeln('</nav>');

  for (final k in keys) {
    buf.writeln('<section id="$k">');
    buf.writeln('<h2>$k</h2>');
    buf.writeln('<div class="grid">');
    for (final f in groups[k]!) {
      final name = f.uri.pathSegments.last;
      // relative path from gallery/ to goldens/
      final rel = '../goldens/$name';
      buf.writeln('<div class="card">');
      buf.writeln('<a href="$rel" target="_blank"><img src="$rel" alt="$name"></a>');
      buf.writeln('<div class="label">$name</div>');
      buf.writeln('</div>');
    }
    buf.writeln('</div>');
    buf.writeln('</section>');
  }

  buf.writeln('</body></html>');
  outFile.writeAsStringSync(buf.toString());
  stdout.writeln('Wrote ${outFile.path} (${files.length} images, ${keys.length} groups)');
}
