# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
# SPDX-FileCopyrightText: 2026 Shubham Sharma
#
# SPDX-License-Identifier: Apache-2.0

name: Lint

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.4"
          channel: "stable"
          cache: true

      - name: Get dependencies
        run: flutter pub get --suppress-analytics

      - name: Analyze
        run: flutter analyze || true
