# SPDX-FileCopyrightText: 2019-2021 Vishesh Handa <me@vhanda.in>
# SPDX-FileCopyrightText: 2026 Shubham Sharma
#
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  workflow_dispatch:

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.47.4"
          channel: "stable"
          cache: true
      - run: flutter pub get --suppress-analytics
      - run: flutter analyze || true
